### ISSUE TITLE
mintty.exe exits unusually when call 'Open' in context menu 

### ISSUE THREAD

**Issue by Jactry** [fracting/wine-fracting#1]
wine version: commit 07b22786b07d443c2b37cf9f3fadca0b36e2084a

Steps for reproducing:
1. Select anything in mintty console;
2. Call context menu and click 'Open';
3. If the selected text is a txt file, it'll be opened by notepad and then mintty will exit.

The last line of the output log:
err:seh:raise_exception Exception frame is not in stack limits => unable to dispatch exception.

**Comment by fracting** [comment]
Thanks for reporting! I didn't know there is such an interesting feature!
Anyway it doesn't crash here with latest wine-staging, could you retest?
BTW I'm testing on 32 bit Ubuntu Linux.

**Comment by fracting** [comment]
ping @Jactry ?

**Comment by Jactry** [comment]
I can't reproduce it now too. Maybe it was fixed.
Thanks.
